name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - name: Login to Forgejo Registry
        uses: docker/login-action@v3
        with:
          registry: git.edufeed.org
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: git.edufeed.org/edufeed/edufeed-app:latest
